global:
  scrape_interval: 15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: celery_exporter
    static_configs:
      - targets: ['celery_exporter:9808']
        labels:
          namespace: 'your-namespace-in-k8s'
