{
 "title": "worker tasks",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "${VAR_NAMESPACE}" },
   { "name": "service_name", "label": "service_name", "query": "${VAR_SERVICE_NAME}" }
  ]
 },
 "panels": [
  {
   "title": "Tasks per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_sent_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_received_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_started_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "started"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_succeeded_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "succeeded"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_failed_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_retried_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "retried"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_rejected_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "rejected"
    },
    {
     "expr": "sum(\n    rate(\n        celery_task_revoked_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "revoked"
    }
   ]
  },
  {
   "title": "Tasks runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "99-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.95, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "95-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "90-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.80, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "80-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.70, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "70-ый"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n)",
     "legendFormat": "50-ый"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_succeeded_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_failed_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Runtime. Quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (task, le)\n)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Runtime. Quantile 50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.5, sum(\n        rate(\n            celery_task_runtime_bucket{\n                namespace=\"$namespace\",\n                service_name=\"$service_name\"\n            }[$__rate_interval]\n        )\n    ) by (task, le)\n)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_queue_length{namespace=\"$namespace\", service_name=\"$service_name\"}) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  {
   "title": "Worker up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_worker_up{namespace=\"$namespace\", service_name=\"$service_name\"}) by (worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Tasks active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(celery_worker_tasks_active{namespace=\"$namespace\", service_name=\"$service_name\"}) by (worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Active consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_active_consumer_count{namespace=\"$namespace\", service_name=\"$service_name\"}) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_active_worker_count{namespace=\"$namespace\", service_name=\"$service_name\"}) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  {
   "title": "Active processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(celery_active_process_count{namespace=\"$namespace\", service_name=\"$service_name\"}) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    },
    {}
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_sent_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_received_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_started_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Retried",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_retried_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_rejected_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Revoked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        celery_task_revoked_total{\n            namespace=\"$namespace\", \n            service_name=\"$service_name\"\n        }[$__rate_interval]\n    )\n) by (task)",
     "legendFormat": "{{ task }}"
    }
   ]
  }
 ]
}